name: Update RSS Feeds

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 feedgen requests

      - name: Run feed scripts
        run: |
          python herald_tribune_rss.py
          python mysuncoast_rss.py
          python srqmagazine_rss.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add *.xml
          git commit -m "Auto–update RSS feeds" || echo "No changes to commit"
          git push origin main
